version: '3'
services:
  database:
    image: postgres:10.4
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c 'rm tmp/pids/server.pid 2>/dev/null; bundle exec rails server -b "0.0.0.0"'
    volumes:
      - bundle-volume:/usr/local/bundle
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - database
    tty: true
    stdin_open: true
volumes:
  bundle-volume:
    driver: local
